/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditEntryRouteImport } from './routes/edit-entry'
import { Route as AddEntryRouteImport } from './routes/add-entry'
import { Route as IndexRouteImport } from './routes/index'

const EditEntryRoute = EditEntryRouteImport.update({
  id: '/edit-entry',
  path: '/edit-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AddEntryRoute = AddEntryRouteImport.update({
  id: '/add-entry',
  path: '/add-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-entry': typeof AddEntryRoute
  '/edit-entry': typeof EditEntryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-entry': typeof AddEntryRoute
  '/edit-entry': typeof EditEntryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-entry': typeof AddEntryRoute
  '/edit-entry': typeof EditEntryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-entry' | '/edit-entry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-entry' | '/edit-entry'
  id: '__root__' | '/' | '/add-entry' | '/edit-entry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEntryRoute: typeof AddEntryRoute
  EditEntryRoute: typeof EditEntryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/edit-entry': {
      id: '/edit-entry'
      path: '/edit-entry'
      fullPath: '/edit-entry'
      preLoaderRoute: typeof EditEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-entry': {
      id: '/add-entry'
      path: '/add-entry'
      fullPath: '/add-entry'
      preLoaderRoute: typeof AddEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEntryRoute: AddEntryRoute,
  EditEntryRoute: EditEntryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
